### ISSUE TITLE
This module is not compiling with latest updates

### ISSUE THREAD

**Issue by varosi** [exbb2/http-conduit-browser#13]
Installed aeson-0.7.0.6
Installed tls-1.2.16
Downloading connection-0.2.4...
Configuring connection-0.2.4...
Building connection-0.2.4...
Installed connection-0.2.4
Downloading http-client-tls-0.2.2...
Configuring http-client-tls-0.2.2...
Building http-client-tls-0.2.2...
Installed http-client-tls-0.2.2
Downloading http-conduit-2.0.0.10...
Configuring http-conduit-2.0.0.10...
Building http-conduit-2.0.0.10...
Installed http-conduit-2.0.0.10
Downloading http-conduit-browser-1.7.2...
Configuring http-conduit-browser-1.7.2...
Building http-conduit-browser-1.7.2...
Failed to install http-conduit-browser-1.7.2
Build log ( D:\Project\haskell_luna\SGFetch\.cabal-sandbox\logs\http-conduit-browser-1.7.2.log ):
Building http-conduit-browser-1.7.2...
Preprocessing library http-conduit-browser-1.7.2...

Network\HTTP\Conduit\Browser.hs:222:8:
    Could not find module `Network.HTTP.Conduit.Internal'
    Perhaps you meant
      Network.HTTP.Client.Internal (needs flag -package http-client-0.4.7.2)
    Use -v to see a list of the files searched for.
cabal.exe: Error: some packages failed to install:
SGFetch-0.1 depends on http-conduit-browser-1.7.2 which failed to install.
http-conduit-browser-1.7.2 failed during the building phase. The exception
was:
ExitFailure 1

**Comment by exbb2** [comment]
Now it does.

However this module is deprecated and won't be updated anymore.
